apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app-deployment
  labels:
    app: node-todo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-todo-app
  template:
    metadata:
      labels:
        app: node-todo-app
    spec:
      containers:
      - name: node-todo-app
        image: 154647635698.dkr.ecr.ap-southeast-1.amazonaws.com/todo-app-repo:latest
        imagePullPolicy: Always
        ports:
          - containerPort: 3000

        
     
---
apiVersion: v1
kind: Service
metadata:
  name: node-todo-app-service
spec:
  type: NodePort
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
    nodePort: 30001
  selector:
    app: node-todo-app
