apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app-deployment
  labels:
    app: node-todo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-todo-app
  template:
    metadata:
      labels:
        app: node-todo-app
    spec:
      containers:
      - name: node-todo-app-container
        image: 154647635698.dkr.ecr.ap-southeast-1.amazonaws.com/todo-app-repo:latest
        imagePullPolicy: Always
        ports:
          - name: web
            containerPort: 3000
      imagePullSecrets:
          - name: regcred
        
     
---
apiVersion: v1
kind: Service
metadata:
  name: node-todo-app-service
spec:
  type: NodePort
  ports:
  - port: 3000
  selector:
    app: node-todo-app
